name: Functional Programmer in Motion
author: Benjamin Thuillier
email: benjaminthuillier@gmail.com
github: https://github.com/bthuillier
linkedin: https://www.linkedin.com/in/benjamin-thuillier/
bluesky: https://bsky.app/profile/bthuillier.bsky.social
